LeastAuthority/Transfer

- README.md
A few instructions to run mailbox and relay servers locally during development.
> README: add instructions to run everything locally for dev work

- src/components/receive/ReceiveDefault.vue
- src/store/index.ts
This pull request is a fix for issue #23
> code converted to lower case

- README.md
> README: update with steps to do cloning, installing dependencies etc

- README.md
- Fixes a formatting error: extra "```"
- Renames MyFileTransfer to Transfer (matching the UI)
- Adds some detail to project description and build instructions
---
> Update / fix readme

- src/components/send/SendInstructions.vue
Reorders the instruction copy and code input rows on the send instructions page in accordance with #43.
---
~~- [ ] New code has enough tests.~~
~~- [ ] New code has enough documentation to answer "how do I use it?" and "what does it do?".~~
~~- [ ] Existing documentation is up-to-date, if impacted.~~
> Re-order send instructions

- public/robots.txt
This PR adds a robots.txt file. For now, it deny access to all the crawlers.
Addresses issue: https://app.clickup.com/t/1p7nf11 (closes: CU-1p7nf11)
> robots.txt: disallow every crawler

- src/wordlist/wordlist.ts
- tests/unit/wordlist/wordlist.spec.ts
Hide code word suggestion if partial word isn't a prefix match for any valid code word.
Task ID: 1mrburv
---
> Hide code suggestion if partial word doesn't match

- src/components/Footer.vue
- src/views/Main.vue
- Replace "security" with "FAQ"
- Preserve footer section order (links before LA logo)
- Hide "made with love for privacy by" on mobile
- Make footer only sticky on desktop
- Fix footer links distribution and alignment
---
> Mobile footer changes

- src/components/Footer.vue
- src/views/Main.vue
- Left margin of "Transfer" title aligned with card subtitle text "Send
files..."
- Set right margin of nav button equal to left margin of "Transfer" text
---
> Fix margins

- src/components/Card.vue
- src/components/Footer.vue
- src/views/Main.vue
> Set responsive font sizes in rem units

- src/go/wormhole/client.ts
- src/go/wormhole/client_worker.ts
- src/go/wormhole/types.ts
- src/worker.ts
- tests/unit/cancellation.spec.ts
> Disable send side streaming

- tests/e2e/specs/error.spec.ts
- tests/e2e/specs/receive.spec.ts
- tests/e2e/support/util.ts
- tests/unit/cancellation.spec.ts
- tests/unit/streaming.spec.ts
> fix errors reported by yarn lint

- .github/workflows/main.yml
- .gitmodules
- package.json
- tests/unit/streaming.spec.ts
This sets up CI based on Github Actions. A local versions of mailbox server and relay server is also run. The commit also updates transfer repo to point to the latest commit on the relay server. Once the relay server makes a release which contains the websocket relay support, we would have to switch the CI to use the released version from PYPI.
Closes #69 
---
> Setup github actions

- src/components/Card.vue
- src/components/CardModal.vue
- src/components/Footer.vue
- src/components/Progress.vue
- src/components/Version.vue
- src/components/receive/ReceiveComplete.vue
- src/components/receive/ReceiveConsent.vue
- src/components/receive/ReceiveDefault.vue
- src/components/receive/ReceiveProgress.vue
- src/components/send/DropZone.vue
- src/components/send/SendComplete.vue
- src/components/send/SendDefault.vue
- src/components/send/SendInstructions.vue
- src/components/send/SendProgress.vue
- src/version.ts
- src/views/Main.vue
- src/views/Receive.vue
- src/views/Send.vue
- src/wordlist/wordlist.ts
This refactor reduces the effort involved in making layout and styling changes across multiple views going forward.
---
> Factor out common view structure

- src/go/wormhole/client.ts
- src/go/wormhole/types.ts
- src/worker.ts
- tests/e2e/support/util.ts
- tests/unit/streaming.spec.ts
> re-introduce send-side streaming

- scripts/deploy.js
- src/go/wormhole/client.ts
- src/store/index.ts
TODO: add a build script analogous to the deploy and uncache scripts, which uses dotenv to load these new environment variables, defaulting to their respective local development environment values:
- `STAGE_HOSTNAME`
- `STAGE_MAILBOX_URL`
- `STAGE_RELAY_URL`
---
> Move backend config out of the code

- src/errors.ts
- src/go/wormhole/client_worker.ts
> Error code and text for receive connection timeout

- src/go/wormhole/client_worker.ts
> bug fix: uninitialized variable causes runtime crash

- changelog.md
- src/version.ts
Release branch with changes for v0.0.4.alpha.plus.rc2
---
- ~[ ] New code has enough tests.~
- ~[ ] New code has enough documentation to answer "how do I use it?" and "what does it do?".~
> Release v0.0.4 alpha.plus.rc2

- changelog.md
- src/version.ts
Fixes the broken earlier rc2 deployment on playground which was incorrectly trying to use localhost for the backend servers because the environment variables that sets the playground backend URLs were not propagated into the source code at build time. The current changes instead use runtime configuration.
---
> Release v0.0.4 alpha.plus.rc3

- changelog.md
- src/version.ts
0.0.4 alpha+ rc4 release. Please check the changelog.md for the changes.
---
> Release v0.0.4 alpha.plus.rc4

- .github/workflows/main.yml
> CI: build the dist directory

- README.md
- scripts/build.js
- src/store/index.ts
> Move config out of source code and expect it to be defined in .env files

- .github/workflows/main.yml
- .gitmodules
- docker/relay/Dockerfile
> get rid of the relay server submodule

- README.md
> README: update to use the current repository name

- changelog.md
- package.json
- src/version.ts
new release 0.0.4.alpha+.rc5
---
> bump up the version to v0.0.4.alpha.plus.rc5

- src/errors.ts
- src/store/index.ts
> Fix handling of ErrBadCode

- docker/docker-compose.yml
- docker/relay/Dockerfile
- docker/relay/Pipfile
Also cleans up the Dockerfile.
OP#714
---
> docker: transit-relay submodule has been removed, so remove references

- changelog.md
- src/version.ts
tested locally with:
`yarn build:playground`
`npx serve ./dist`
and doing a few file transfers.
---
> Release v0.0.4 alpha.plus.rc6

- package.json
- scripts/build.js
> Fix worker not building to `dest/`

- src/components/Progress.vue
- src/components/receive/ReceiveConsent.vue
- src/components/receive/ReceiveProgress.vue
- src/components/send/SendInstructions.vue
- src/components/send/SendProgress.vue
- src/errors.ts
- src/go/wormhole/client_worker.ts
> Implement cancellation workaround

- src/views/Receive.vue
> Fix code URL not working if replaced on site

- src/errors.ts
- src/go/wormhole/client_worker.ts
> Change cancellation error message

- CHANGELOG.md
Updated changelong to reflect latest bugfixes before release alpha+ version. Also change file name to capitals to keep the same logic as with README.md
---
> Update and rename changelog.md to CHANGELOG.md
